{
  "created": 1615996830.1041288,
  "duration": 0.0627129077911377,
  "exitcode": 1,
  "root": "/home/kevin/.scripts/test_wrappers",
  "environment": {
    "Python": "3.8.5",
    "Platform": "Linux-5.8.0-45-generic-x86_64-with-glibc2.29",
    "Packages": { "pytest": "6.2.2", "py": "1.10.0", "pluggy": "0.13.1" },
    "Plugins": {
      "cov": "2.11.1",
      "testmon": "1.0.3",
      "json-report": "1.2.4",
      "metadata": "1.11.0",
      "forked": "1.3.0",
      "django": "4.1.0",
      "xdist": "2.2.1",
      "Faker": "6.1.1"
    }
  },
  "summary": { "passed": 3, "failed": 1, "total": 4, "collected": 4 },
  "collectors": [
    {
      "nodeid": "",
      "outcome": "passed",
      "result": [
        { "nodeid": "src/__init__.py", "type": "Package" },
        { "nodeid": "src/common/__init__.py", "type": "Package" },
        { "nodeid": "src/pytest/__init__.py", "type": "Package" }
      ]
    },
    { "nodeid": "src/__init__.py", "outcome": "passed", "result": [] },
    { "nodeid": "src/common/__init__.py", "outcome": "passed", "result": [] },
    {
      "nodeid": "src/pytest/test_pytest.py",
      "outcome": "passed",
      "result": [
        {
          "nodeid": "src/pytest/test_pytest.py::test_no_failures",
          "type": "Function",
          "lineno": 10
        },
        {
          "nodeid": "src/pytest/test_pytest.py::test_skipped_test",
          "type": "Function",
          "lineno": 20
        },
        {
          "nodeid": "src/pytest/test_pytest.py::test_failure_in_test",
          "type": "Function",
          "lineno": 43
        },
        {
          "nodeid": "src/pytest/test_pytest.py::test_syntax_error",
          "type": "Function",
          "lineno": 60
        }
      ]
    },
    {
      "nodeid": "src/pytest/__init__.py",
      "outcome": "passed",
      "result": [{ "nodeid": "src/pytest/test_pytest.py", "type": "Module" }]
    }
  ],
  "tests": [
    {
      "nodeid": "src/pytest/test_pytest.py::test_no_failures",
      "lineno": 10,
      "outcome": "passed",
      "keywords": [
        "src/pytest/__init__.py",
        "test_pytest.py",
        "test_wrappers",
        "test_no_failures"
      ],
      "setup": { "duration": 0.020199997998133767, "outcome": "passed" },
      "call": { "duration": 0.0002812650018313434, "outcome": "passed" },
      "teardown": { "duration": 0.00021350899987737648, "outcome": "passed" }
    },
    {
      "nodeid": "src/pytest/test_pytest.py::test_skipped_test",
      "lineno": 20,
      "outcome": "passed",
      "keywords": [
        "test_skipped_test",
        "src/pytest/__init__.py",
        "test_pytest.py",
        "test_wrappers"
      ],
      "setup": { "duration": 0.0005285770021146163, "outcome": "passed" },
      "call": { "duration": 0.0002673189992492553, "outcome": "passed" },
      "teardown": { "duration": 0.0001929200006998144, "outcome": "passed" }
    },
    {
      "nodeid": "src/pytest/test_pytest.py::test_failure_in_test",
      "lineno": 43,
      "outcome": "passed",
      "keywords": [
        "test_failure_in_test",
        "test_pytest.py",
        "src/pytest/__init__.py",
        "test_wrappers"
      ],
      "setup": { "duration": 0.0005209829978412017, "outcome": "passed" },
      "call": { "duration": 0.0002766070028883405, "outcome": "passed" },
      "teardown": { "duration": 0.0002221850008936599, "outcome": "passed" }
    },
    {
      "nodeid": "src/pytest/test_pytest.py::test_syntax_error",
      "lineno": 60,
      "outcome": "failed",
      "keywords": [
        "test_syntax_error",
        "src/pytest/__init__.py",
        "test_pytest.py",
        "test_wrappers"
      ],
      "setup": { "duration": 0.0005368220008676872, "outcome": "passed" },
      "call": {
        "duration": 0.00016412700279033743,
        "outcome": "failed",
        "crash": {
          "path": "/home/kevin/.scripts/test_wrappers/src/pytest/test_pytest.py",
          "lineno": 62,
          "message": "NameError: name 'mischief' is not defined"
        },
        "traceback": [
          {
            "path": "src/pytest/test_pytest.py",
            "lineno": 62,
            "message": "NameError"
          }
        ],
        "longrepr": "def test_syntax_error():\n>       mischief\nE       NameError: name 'mischief' is not defined\n\nsrc/pytest/test_pytest.py:62: NameError"
      },
      "teardown": { "duration": 0.0004913269985991064, "outcome": "passed" }
    }
  ]
}
